### ISSUE TITLE
in case of solr error in python 3.4, pysolr tries to replace strings in bytes type

### ISSUE THREAD

**Issue by Fiedzia** [toastdriven/pysolr#136]
I've tried to index list of values in a field that wasn't set as multivalued.
On parsing solr error, pysolr does this:

 full_html = full_html.replace('\n', '')

but full_html is bytes, so it fails.

 File "../venv/lib/python3.4/site-packages/pysolr.py", line 467, in _scrape_response
    full_html = full_html.replace('\n', '')
TypeError: expected bytes, bytearray or buffer compatible object

**Comment by alexef** [comment]
This was fixed in commit: https://github.com/toastdriven/pysolr/commit/e403572e585204a2ee01293af4d248a1df98cf07

What version of pysolr are you using?

**Comment by toastdriven** [comment]
pysolr 3.3.0 has been released (https://pypi.python.org/pypi/pysolr/3.3.0) & includes that commit. I'd recommend upgrading & trying again.
