### ISSUE TITLE
pip install broken since update to 3.3.1

### ISSUE THREAD

**Issue by artyom** [toastdriven/pysolr#154]
Install on linux amd64 via `pip install` is broken since May 12 — tarball for invalid platform is being downloaded:

	Downloading/unpacking pysolr (from -r requirements.pip (line 30))
	  Downloading pysolr-3.3.1.macosx-10.10-x86_64.tar.gz
	  Running setup.py egg_info for package pysolr
	    Traceback (most recent call last):
	      File "<string>", line 14, in <module>
	    IOError: [Errno 2] No such file or directory: '/home/ec2-user/env/build/pysolr/setup.py'
	    Complete output from command python setup.py egg_info:
	    Traceback (most recent call last):
	
	  File "<string>", line 14, in <module>
	
	IOError: [Errno 2] No such file or directory: '/home/ec2-user/env/build/pysolr/setup.py'
	
	----------------------------------------
	Command python setup.py egg_info failed with error code 1 in /home/ec2-user/env/build/pysolr

**Comment by acdha** [comment]
This doesn't reproduce on any system I have access to (various Ubuntu / Debian releases). Is it possible that this is a really old version of pip / setuptools?

**Comment by artyom** [comment]
Looks like this issue is really reproduced only on older pip versions: I've used pip from Debian Wheezy (oldstable) with `python-virtualenv` package installed and the error above happens when `requirements.pip` file has `pysolr` dependency listed without version specified — this was caught by automated process of daily docker container build.

I've updated pip and the problem is gone; I suggest this issue can be closed then.

Thank you!

**Comment by acdha** [comment]
@artyom Thanks for confirming that I wasn't going crazy ;-) 

Since the only binary package was for OS X and pysolr is so lightweight, I just “fixed” this by deleting the binary package so everyone will get the source install. I probably should look into uploading wheels but I'm not sure that's worth much for a pure-python single-file library.
