### ISSUE TITLE
v3.3.2 not tagged in git

### ISSUE THREAD

**Issue by frewsxcv** [toastdriven/pysolr#157]

**Comment by frewsxcv** [comment]
@acdha You deserve a cake for the turnaround time for this issue

![](http://crossfit601.com/wp-content/uploads/2015/03/article-0-14FA374C000005DC-973_634x467.jpg)

**Comment by acdha** [comment]
Possibly some egg on my face for tagging it when I did the release but forgetting to actually *push* the tag out to where you could see it… ;)

**Comment by frewsxcv** [comment]
:P
