### ISSUE TITLE
Configurable search endpoint

### ISSUE THREAD

**Issue by aarcro** [toastdriven/pysolr#174]
# Story
As an advanced solr user
I want to direct search queries to multiple searchHandlers
So that I can have a variety of default filters applied in solr

# Implementation
I see two options for this. Either adding a property to `class Solr` that can set the search endpoint at initialization time. Or an optional parameter to `def search` and `def _select` to specify the endpoint in a one off fashion.

# Acceptance Criteria
_Given_ a solr searchHandler located at localhost:8983/solr/search2/
_When_ I call solr.search
_Then_ The query is sent to localhost:8983/solr/search2/

**Comment by acdha** [comment]
I believe you could do this simply by twiddling the `.url` property now since it's just joining them (https://github.com/toastdriven/pysolr/blob/master/pysolr.py#L331-L336) but that's definitely inelegant. If you wanted to send in a pull request making path configurable I'd support that.

**Comment by aarcro** [comment]
Thanks @acdha We'll work on a pull request for this. Leaning towards an additional argument for search and _select... which makes _select a bit of a misnomer.

**Comment by acdha** [comment]
Yes - if you see opportunities to refactor either open separate pull
requests or issues. pysolr has grown considerably since its beginnings and
there's definitely room for improvement.
